import { randomHex, randomPassword } from "./secrets.js";
import { requiredEnvVarsFor } from "./tls/lego-providers.js";

export type ProvisionerMode = "docker" | "dokploy-remote";

export type TlsMode = "auto" | "public-alpn" | "dns-01" | "self-ca";
const VALID_TLS_MODES: readonly TlsMode[] = [
  "auto",
  "public-alpn",
  "dns-01",
  "self-ca",
] as const;

export interface InstallConfig {
  mode: ProvisionerMode;
  domain: string;
  /**
   * Hostname stamped into local-docker deploy URLs (http://<host>:<port>).
   * Empty = inherit DOMAIN at compose time (good for real-TLD installs).
   * Localhost-domain installs should set this to the box's LAN IP so
   * deploy URLs are reachable from the operator's browser.
   */
  publicHost: string;
  /**
   * uid:gid to chown the install repo back to after any root-run update.
   * install.sh captures this pre-sudo; installer renders it into .env so
   * the server container receives it and can pass it to the updater.
   */
  ownerUidGid: string;
  tlsEmail: string;
  adminPassword: string;

  infisicalDbPassword: string;
  infisicalRedisPassword: string;
  infisicalEncryptionKey: string;
  infisicalAuthSecret: string;

  // Populated AFTER Infisical comes up + installer provisions identity.
  infisicalProjectId: string;
  infisicalClientId: string;
  infisicalClientSecret: string;

  // Infisical console login (admin user created during bootstrap). Persisted
  // to .env so the operator can retrieve them later via the web UI reveal
  // flow on the Secrets page — Infisical ships with self-registration
  // disabled, so losing these would lock the console out.
  infisicalAdminEmail: string;
  infisicalAdminPassword: string;

  // Dokploy-remote only.
  dokployUrl: string;
  dokployApiToken: string;
  dokployProjectId: string;
  dokployEnvironmentId: string;

  // Image tags (defaults work for npx install).
  serverImage: string;
  workspaceImage: string;

  tlsMode: TlsMode;
  tlsDnsProvider: string;
  tlsDnsEnvVars: Record<string, string>;
  /**
   * Self-CA only: comma-separated list of IPs to include in the leaf cert SAN.
   * Auto-detected by run.ts/headless when self-ca mode is selected and this
   * is empty; user can override via AGENTHUB_LAN_IP or the TUI prompt.
   */
  lanIp: string;
}

export function emptyConfig(): InstallConfig {
  return {
    mode: "docker",
    domain: "localhost",
    publicHost: "",
    ownerUidGid: "",
    tlsEmail: "",
    adminPassword: "",
    infisicalDbPassword: randomPassword(32),
    infisicalRedisPassword: randomPassword(32),
    infisicalEncryptionKey: randomHex(16),
    infisicalAuthSecret: randomPassword(48),
    infisicalProjectId: "",
    infisicalClientId: "",
    infisicalClientSecret: "",
    infisicalAdminEmail: "",
    infisicalAdminPassword: "",
    dokployUrl: "",
    dokployApiToken: "",
    dokployProjectId: "",
    dokployEnvironmentId: "",
    serverImage: "ghcr.io/physikal/agenthubv2-server:latest",
    workspaceImage: "ghcr.io/physikal/agenthubv2-workspace:latest",
    tlsMode: "auto",
    tlsDnsProvider: "",
    tlsDnsEnvVars: {},
    lanIp: "",
  };
}

export function renderEnv(cfg: InstallConfig): string {
  // For localhost installs the user typically reaches the box by LAN IP or
  // SSH tunnel, so a strict Host(localhost) rule locks them out. PathPrefix(/)
  // accepts any Host header. For real domains we keep the strict Host() rule
  // so production can't be reached via arbitrary hostnames.
  const hostRule =
    cfg.domain === "localhost"
      ? "PathPrefix(`/`)"
      : `Host(\`${cfg.domain}\`)`;

  // Absolute host path of the install's git checkout. Mounted read-write
  // into the server container at /repo so the server can read git state
  // (for /api/admin/version) and trigger updates via the agenthubv2-updater
  // image. Relative paths don't work here because docker-compose resolves
  // them from the compose file when first invoked, but the updater container
  // later invokes `docker compose up -d` with the same compose file and
  // expects the host-level absolute path.
  const repoDir = process.cwd();

  return [
    "# Generated by agenthub-install",
    ...(cfg.domain === "localhost"
      ? []
      : ["COMPOSE_FILE=docker-compose.yml:traefik.override.yml"]),
    `DOMAIN=${cfg.domain}`,
    `TLS_EMAIL=${cfg.tlsEmail}`,
    `AGENTHUB_HOST_RULE=${hostRule}`,
    `AGENTHUB_PUBLIC_HOST=${cfg.publicHost}`,
    `AGENTHUB_REPO_DIR=${repoDir}`,
    `AGENTHUB_OWNER=${cfg.ownerUidGid}`,
    "",
    `PROVISIONER_MODE=${cfg.mode}`,
    `DOCKER_HOST=`,
    `DOKPLOY_URL=${cfg.dokployUrl}`,
    `DOKPLOY_API_TOKEN=${cfg.dokployApiToken}`,
    `DOKPLOY_PROJECT_ID=${cfg.dokployProjectId}`,
    `DOKPLOY_ENVIRONMENT_ID=${cfg.dokployEnvironmentId}`,
    "",
    `AGENTHUB_SERVER_IMAGE=${cfg.serverImage}`,
    `WORKSPACE_IMAGE=${cfg.workspaceImage}`,
    "",
    `INFISICAL_DB_PASSWORD=${cfg.infisicalDbPassword}`,
    `INFISICAL_REDIS_PASSWORD=${cfg.infisicalRedisPassword}`,
    `INFISICAL_ENCRYPTION_KEY=${cfg.infisicalEncryptionKey}`,
    `INFISICAL_AUTH_SECRET=${cfg.infisicalAuthSecret}`,
    `INFISICAL_PROJECT_ID=${cfg.infisicalProjectId}`,
    `INFISICAL_CLIENT_ID=${cfg.infisicalClientId}`,
    `INFISICAL_CLIENT_SECRET=${cfg.infisicalClientSecret}`,
    `INFISICAL_ENVIRONMENT=prod`,
    `INFISICAL_ADMIN_EMAIL=${cfg.infisicalAdminEmail}`,
    `INFISICAL_ADMIN_PASSWORD=${cfg.infisicalAdminPassword}`,
    "",
    `AGENTHUB_ADMIN_PASSWORD=${cfg.adminPassword}`,
    ...(cfg.lanIp ? [`AGENTHUB_LAN_IP=${cfg.lanIp}`] : []),
    ...(Object.keys(cfg.tlsDnsEnvVars).length > 0
      ? [
          "",
          "# DNS-01 provider env vars (referenced by traefik.override.yml)",
          ...Object.entries(cfg.tlsDnsEnvVars).map(([k, v]) => `${k}=${v}`),
        ]
      : []),
    "",
  ].join("\n");
}

/**
 * Merge env-var overrides onto the generated defaults. Used by the headless
 * (--non-interactive) path so agents can drive the installer via env vars.
 */
export function applyEnvOverrides(
  cfg: InstallConfig,
  env = process.env,
): InstallConfig {
  const next = { ...cfg };
  if (env["AGENTHUB_MODE"]) next.mode = env["AGENTHUB_MODE"] as ProvisionerMode;
  if (env["AGENTHUB_DOMAIN"]) next.domain = env["AGENTHUB_DOMAIN"];
  if (env["AGENTHUB_PUBLIC_HOST"]) next.publicHost = env["AGENTHUB_PUBLIC_HOST"];
  if (env["AGENTHUB_OWNER"]) next.ownerUidGid = env["AGENTHUB_OWNER"];
  if (env["AGENTHUB_TLS_EMAIL"]) next.tlsEmail = env["AGENTHUB_TLS_EMAIL"];
  if (env["AGENTHUB_ADMIN_PASSWORD"]) next.adminPassword = env["AGENTHUB_ADMIN_PASSWORD"];
  if (env["AGENTHUB_DOKPLOY_URL"]) next.dokployUrl = env["AGENTHUB_DOKPLOY_URL"];
  if (env["AGENTHUB_DOKPLOY_API_TOKEN"]) next.dokployApiToken = env["AGENTHUB_DOKPLOY_API_TOKEN"];
  if (env["AGENTHUB_DOKPLOY_PROJECT_ID"]) next.dokployProjectId = env["AGENTHUB_DOKPLOY_PROJECT_ID"];
  if (env["AGENTHUB_DOKPLOY_ENVIRONMENT_ID"]) next.dokployEnvironmentId = env["AGENTHUB_DOKPLOY_ENVIRONMENT_ID"];
  if (env["AGENTHUB_SERVER_IMAGE"]) next.serverImage = env["AGENTHUB_SERVER_IMAGE"];
  if (env["AGENTHUB_WORKSPACE_IMAGE"]) next.workspaceImage = env["AGENTHUB_WORKSPACE_IMAGE"];
  if (env["AGENTHUB_TLS_MODE"]) {
    next.tlsMode = env["AGENTHUB_TLS_MODE"] as TlsMode;
  }
  if (env["AGENTHUB_LAN_IP"]) {
    next.lanIp = env["AGENTHUB_LAN_IP"];
  }
  if (env["AGENTHUB_TLS_DNS_PROVIDER"]) {
    next.tlsDnsProvider = env["AGENTHUB_TLS_DNS_PROVIDER"];
  }
  // Convenience var: AGENTHUB_CLOUDFLARE_API_TOKEN → CF_DNS_API_TOKEN.
  if (env["AGENTHUB_CLOUDFLARE_API_TOKEN"]) {
    next.tlsDnsEnvVars = {
      ...next.tlsDnsEnvVars,
      CF_DNS_API_TOKEN: env["AGENTHUB_CLOUDFLARE_API_TOKEN"],
    };
  }
  // Direct CF_DNS_API_TOKEN (for users who already export the lego-style var).
  if (env["CF_DNS_API_TOKEN"] && !next.tlsDnsEnvVars["CF_DNS_API_TOKEN"]) {
    next.tlsDnsEnvVars = {
      ...next.tlsDnsEnvVars,
      CF_DNS_API_TOKEN: env["CF_DNS_API_TOKEN"],
    };
  }
  // Forward provider-specific env vars: read the lego manifest for the
  // chosen provider, copy any matching vars from the host env. Best-effort
  // for providers we know; users of unknown providers can pre-export and
  // we'll skip-validate at install time, relying on the loud-failure gate.
  if (next.tlsDnsProvider) {
    const requiredVars = requiredEnvVarsFor(next.tlsDnsProvider) ?? [];
    for (const name of requiredVars) {
      const v = env[name];
      if (v && !next.tlsDnsEnvVars[name]) {
        next.tlsDnsEnvVars = { ...next.tlsDnsEnvVars, [name]: v };
      }
    }
  }
  return next;
}

/**
 * For dokploy-remote, surface the env vars that MUST be set. Returns a list
 * of missing var names — empty = ok.
 */
export function missingRequiredForHeadless(cfg: InstallConfig): string[] {
  const missing: string[] = [];
  if (cfg.mode === "dokploy-remote") {
    if (!cfg.dokployUrl) missing.push("AGENTHUB_DOKPLOY_URL");
    if (!cfg.dokployApiToken) missing.push("AGENTHUB_DOKPLOY_API_TOKEN");
    if (!cfg.dokployProjectId) missing.push("AGENTHUB_DOKPLOY_PROJECT_ID");
    if (!cfg.dokployEnvironmentId) missing.push("AGENTHUB_DOKPLOY_ENVIRONMENT_ID");
  }
  if (cfg.domain !== "localhost" && !cfg.tlsEmail) {
    missing.push("AGENTHUB_TLS_EMAIL");
  }
  if (!VALID_TLS_MODES.includes(cfg.tlsMode)) {
    missing.push(
      `AGENTHUB_TLS_MODE (got '${cfg.tlsMode}'; valid: ${VALID_TLS_MODES.join(", ")})`,
    );
  }
  if (cfg.tlsMode === "dns-01" || (cfg.tlsMode === "auto" && cfg.tlsDnsProvider)) {
    if (!cfg.tlsDnsProvider) {
      missing.push("AGENTHUB_TLS_DNS_PROVIDER");
    } else if (cfg.tlsDnsProvider === "cloudflare") {
      if (!cfg.tlsDnsEnvVars["CF_DNS_API_TOKEN"]) {
        missing.push("AGENTHUB_CLOUDFLARE_API_TOKEN (or CF_DNS_API_TOKEN)");
      }
    } else {
      const required = requiredEnvVarsFor(cfg.tlsDnsProvider);
      if (required) {
        for (const name of required) {
          if (!cfg.tlsDnsEnvVars[name]) missing.push(name);
        }
      }
      // Unknown provider: no manifest, can't validate. Loud-failure gate at
      // install time will surface a wrong/missing token via the cert probe.
    }
  }
  return missing;
}
