import { randomHex, randomPassword } from "./secrets.js";

export type ProvisionerMode = "docker" | "dokploy-local" | "dokploy-remote";

export interface InstallConfig {
  mode: ProvisionerMode;
  domain: string;
  tlsEmail: string;
  adminPassword: string;

  infisicalDbPassword: string;
  infisicalRedisPassword: string;
  infisicalEncryptionKey: string;
  infisicalAuthSecret: string;

  // Populated AFTER Infisical comes up + installer provisions identity.
  infisicalProjectId: string;
  infisicalClientId: string;
  infisicalClientSecret: string;

  // Dokploy-remote only.
  dokployUrl: string;
  dokployApiToken: string;
  dokployProjectId: string;
  dokployEnvironmentId: string;

  // Dokploy-local overlay only.
  dokployDbPassword: string;

  // Image tags (defaults work for npx install).
  serverImage: string;
  workspaceImage: string;
}

export function emptyConfig(): InstallConfig {
  return {
    mode: "docker",
    domain: "localhost",
    tlsEmail: "",
    adminPassword: "",
    infisicalDbPassword: randomPassword(32),
    infisicalRedisPassword: randomPassword(32),
    infisicalEncryptionKey: randomHex(16),
    infisicalAuthSecret: randomPassword(48),
    infisicalProjectId: "",
    infisicalClientId: "",
    infisicalClientSecret: "",
    dokployUrl: "",
    dokployApiToken: "",
    dokployProjectId: "",
    dokployEnvironmentId: "",
    dokployDbPassword: randomPassword(32),
    serverImage: "ghcr.io/physikal/agenthubv2-server:latest",
    workspaceImage: "ghcr.io/physikal/agenthubv2-workspace:latest",
  };
}

export function renderEnv(cfg: InstallConfig): string {
  // For localhost installs the user typically reaches the box by LAN IP or
  // SSH tunnel, so a strict Host(localhost) rule locks them out. PathPrefix(/)
  // accepts any Host header. For real domains we keep the strict Host() rule
  // so production can't be reached via arbitrary hostnames.
  const hostRule =
    cfg.domain === "localhost"
      ? "PathPrefix(`/`)"
      : `Host(\`${cfg.domain}\`)`;

  // Absolute host path of the install's git checkout. Mounted read-write
  // into the server container at /repo so the server can read git state
  // (for /api/admin/version) and trigger updates via the agenthubv2-updater
  // image. Relative paths don't work here because docker-compose resolves
  // them from the compose file when first invoked, but the updater container
  // later invokes `docker compose up -d` with the same compose file and
  // expects the host-level absolute path.
  const repoDir = process.cwd();

  return [
    "# Generated by agenthub-install",
    `DOMAIN=${cfg.domain}`,
    `TLS_EMAIL=${cfg.tlsEmail}`,
    `AGENTHUB_HOST_RULE=${hostRule}`,
    `AGENTHUB_REPO_DIR=${repoDir}`,
    "",
    `PROVISIONER_MODE=${cfg.mode}`,
    `DOCKER_HOST=`,
    `DOKPLOY_URL=${cfg.dokployUrl}`,
    `DOKPLOY_API_TOKEN=${cfg.dokployApiToken}`,
    `DOKPLOY_PROJECT_ID=${cfg.dokployProjectId}`,
    `DOKPLOY_ENVIRONMENT_ID=${cfg.dokployEnvironmentId}`,
    `DOKPLOY_DB_PASSWORD=${cfg.dokployDbPassword}`,
    "",
    `AGENTHUB_SERVER_IMAGE=${cfg.serverImage}`,
    `WORKSPACE_IMAGE=${cfg.workspaceImage}`,
    "",
    `INFISICAL_DB_PASSWORD=${cfg.infisicalDbPassword}`,
    `INFISICAL_REDIS_PASSWORD=${cfg.infisicalRedisPassword}`,
    `INFISICAL_ENCRYPTION_KEY=${cfg.infisicalEncryptionKey}`,
    `INFISICAL_AUTH_SECRET=${cfg.infisicalAuthSecret}`,
    `INFISICAL_PROJECT_ID=${cfg.infisicalProjectId}`,
    `INFISICAL_CLIENT_ID=${cfg.infisicalClientId}`,
    `INFISICAL_CLIENT_SECRET=${cfg.infisicalClientSecret}`,
    `INFISICAL_ENVIRONMENT=prod`,
    "",
    `AGENTHUB_ADMIN_PASSWORD=${cfg.adminPassword}`,
    "",
  ].join("\n");
}

/**
 * Merge env-var overrides onto the generated defaults. Used by the headless
 * (--non-interactive) path so agents can drive the installer via env vars.
 */
export function applyEnvOverrides(
  cfg: InstallConfig,
  env = process.env,
): InstallConfig {
  const next = { ...cfg };
  if (env["AGENTHUB_MODE"]) next.mode = env["AGENTHUB_MODE"] as ProvisionerMode;
  if (env["AGENTHUB_DOMAIN"]) next.domain = env["AGENTHUB_DOMAIN"];
  if (env["AGENTHUB_TLS_EMAIL"]) next.tlsEmail = env["AGENTHUB_TLS_EMAIL"];
  if (env["AGENTHUB_ADMIN_PASSWORD"]) next.adminPassword = env["AGENTHUB_ADMIN_PASSWORD"];
  if (env["AGENTHUB_DOKPLOY_URL"]) next.dokployUrl = env["AGENTHUB_DOKPLOY_URL"];
  if (env["AGENTHUB_DOKPLOY_API_TOKEN"]) next.dokployApiToken = env["AGENTHUB_DOKPLOY_API_TOKEN"];
  if (env["AGENTHUB_DOKPLOY_PROJECT_ID"]) next.dokployProjectId = env["AGENTHUB_DOKPLOY_PROJECT_ID"];
  if (env["AGENTHUB_DOKPLOY_ENVIRONMENT_ID"]) next.dokployEnvironmentId = env["AGENTHUB_DOKPLOY_ENVIRONMENT_ID"];
  if (env["AGENTHUB_SERVER_IMAGE"]) next.serverImage = env["AGENTHUB_SERVER_IMAGE"];
  if (env["AGENTHUB_WORKSPACE_IMAGE"]) next.workspaceImage = env["AGENTHUB_WORKSPACE_IMAGE"];
  return next;
}

/**
 * For dokploy-remote, surface the env vars that MUST be set. Returns a list
 * of missing var names — empty = ok.
 */
export function missingRequiredForHeadless(cfg: InstallConfig): string[] {
  const missing: string[] = [];
  if (cfg.mode === "dokploy-remote") {
    if (!cfg.dokployUrl) missing.push("AGENTHUB_DOKPLOY_URL");
    if (!cfg.dokployApiToken) missing.push("AGENTHUB_DOKPLOY_API_TOKEN");
    if (!cfg.dokployProjectId) missing.push("AGENTHUB_DOKPLOY_PROJECT_ID");
    if (!cfg.dokployEnvironmentId) missing.push("AGENTHUB_DOKPLOY_ENVIRONMENT_ID");
  }
  if (cfg.domain !== "localhost" && !cfg.tlsEmail) {
    missing.push("AGENTHUB_TLS_EMAIL");
  }
  return missing;
}
