import { describe, expect, it } from "vitest";

import { renderGitConfig } from "./github-credentials.js";

describe("renderGitConfig", () => {
  const out = renderGitConfig("physikal");

  it("does NOT embed a token anywhere — credential helper handles auth", () => {
    expect(out).not.toMatch(/ghs_/);
    expect(out).not.toMatch(/x-access-token:/);
    expect(out).not.toMatch(/password=/);
  });

  it("rewrites ssh github urls to https so the helper can fill creds", () => {
    expect(out).toContain(`[url "https://github.com/"]`);
    expect(out).toContain(`insteadOf = git@github.com:`);
  });

  it("sets git user.name + email from the account login", () => {
    expect(out).toContain("name = physikal");
    expect(out).toContain("email = physikal@users.noreply.github.com");
  });

  it("wires the credential helper at the expected path, resetting defaults", () => {
    // `helper = ""` first resets any inherited system/global helper chain;
    // then our helper is the only one used for github.com. useHttpPath
    // keeps the helper keyed on just host (not full URL) so multi-repo
    // fetches share cached tokens correctly.
    expect(out).toMatch(/helper = ""\s*\n\s*helper = \/opt\/agenthub-agent\/git-credential-agenthub/);
    expect(out).toMatch(/useHttpPath = false/);
  });

  it("documents that it's regenerated + token-free (for backups/snapshots)", () => {
    expect(out).toMatch(/Generated by agenthub-agent/);
    expect(out).toMatch(/Tokens are NOT stored here/);
  });
});
