import { writeFileSync, chmodSync, chownSync } from "node:fs";

const CODER_HOME = "/home/coder";
const GITCONFIG_PATH = `${CODER_HOME}/.gitconfig`;

/**
 * Render the ~/.gitconfig content that swaps outbound GitHub clone/push
 * URLs for token-bearing ones via `url.<prefix>.insteadOf`. x-access-token
 * is GitHub's magic username for App installation tokens — the actual
 * credential is the token itself, passed via the URL userinfo.
 *
 * The [user] block is a UX nicety so `git commit` inside a fresh session
 * doesn't yell "please tell me who you are"; the account login is what
 * the token would author as anyway.
 */
export function renderGitConfig(accountLogin: string): string {
  return `# Generated by agenthub-agent. Do not edit — overwritten on session boot.
#
# Tokens are NOT stored here. The credential helper fetches a fresh 1-hour
# GitHub App installation token from the AgentHub server per git operation,
# so ~/.gitconfig stays safe to include in backups / snapshots / ps auxe
# output.

[url "https://github.com/"]
    insteadOf = git@github.com:

[user]
    name = ${accountLogin}
    email = ${accountLogin}@users.noreply.github.com

[credential "https://github.com"]
    helper = ""
    helper = /opt/agenthub-agent/git-credential-agenthub
    useHttpPath = false
`;
}

/**
 * Write ~/.gitconfig pointing at the credential-helper script. No-op unless
 * GITHUB_ACCOUNT_LOGIN was injected by SessionManager (set when the user
 * has an active GitHub App install). The file itself contains NO tokens —
 * the helper script at /opt/agenthub-agent/git-credential-agenthub fetches
 * a fresh short-lived token from the server per git operation.
 *
 * File is mode 0600 + owned uid/gid 1000 (coder user inside the workspace).
 * Even though this file has no secrets, keeping it 0600 mirrors the rest of
 * the workspace's sensitive-file posture.
 */
export function installGitCredentialsFromEnv(): void {
  const login = process.env["GITHUB_ACCOUNT_LOGIN"];
  if (!login) return;
  try {
    writeFileSync(GITCONFIG_PATH, renderGitConfig(login), {
      encoding: "utf8",
      mode: 0o600,
    });
    chmodSync(GITCONFIG_PATH, 0o600);
    chownSync(GITCONFIG_PATH, 1000, 1000);
    console.log(
      `[agent] wrote ${GITCONFIG_PATH} (GitHub App credential helper for ${login})`,
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.warn(`[agent] failed to write ${GITCONFIG_PATH}: ${msg}`);
  }
}
