import { writeFileSync, chmodSync, chownSync } from "node:fs";

const CODER_HOME = "/home/coder";
const GITCONFIG_PATH = `${CODER_HOME}/.gitconfig`;

/**
 * Render the ~/.gitconfig content that swaps outbound GitHub clone/push
 * URLs for token-bearing ones via `url.<prefix>.insteadOf`. x-access-token
 * is GitHub's magic username for App installation tokens — the actual
 * credential is the token itself, passed via the URL userinfo.
 *
 * The [user] block is a UX nicety so `git commit` inside a fresh session
 * doesn't yell "please tell me who you are"; the account login is what
 * the token would author as anyway.
 */
export function renderGitConfig(token: string, accountLogin: string): string {
  return `# Generated by agenthub-agent from the user's GitHub App installation.
# Regenerated on every token refresh. Do not edit — the agent overwrites.

[url "https://x-access-token:${token}@github.com/"]
    insteadOf = https://github.com/
    insteadOf = git@github.com:

[user]
    name = ${accountLogin}
    email = ${accountLogin}@users.noreply.github.com

[credential]
    # Fall back to an in-flight token if an https:// URL somehow bypasses
    # the url-rewrite above (some tools such as gh append their own paths).
    helper = !f() { echo username=x-access-token; echo "password=${token}"; }; f
`;
}

/**
 * Write ~/.gitconfig with the given App installation token, if it's set.
 * No-op when GITHUB_TOKEN is absent so the legacy PAT flow keeps working
 * for users who haven't installed the App yet.
 *
 * The file is mode 0600 + owned by uid/gid 1000 (the coder user inside
 * the workspace). The token is never logged — we echo it only into the
 * file contents, then drop the reference so it can be GC'd.
 */
export function installGitCredentialsFromEnv(): void {
  const token = process.env["GITHUB_TOKEN"];
  const login = process.env["GITHUB_ACCOUNT_LOGIN"];
  if (!token) return;
  const accountLogin = login && login.length > 0 ? login : "agenthub";
  try {
    writeFileSync(GITCONFIG_PATH, renderGitConfig(token, accountLogin), {
      encoding: "utf8",
      mode: 0o600,
    });
    chmodSync(GITCONFIG_PATH, 0o600);
    chownSync(GITCONFIG_PATH, 1000, 1000);
    console.log(
      `[agent] wrote ${GITCONFIG_PATH} (GitHub App token for ${accountLogin})`,
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.warn(`[agent] failed to write ${GITCONFIG_PATH}: ${msg}`);
  }
}
