import { describe, expect, it } from "vitest";

import { renderGitConfig } from "./github-credentials.js";

describe("renderGitConfig", () => {
  const out = renderGitConfig("ghs_token123", "physikal");

  it("embeds the token in the url-rewrite insteadOf rule", () => {
    expect(out).toContain(
      `[url "https://x-access-token:ghs_token123@github.com/"]`,
    );
    expect(out).toContain(`insteadOf = https://github.com/`);
    expect(out).toContain(`insteadOf = git@github.com:`);
  });

  it("sets git user.name + email from the account login", () => {
    expect(out).toContain("name = physikal");
    expect(out).toContain("email = physikal@users.noreply.github.com");
  });

  it("includes a credential helper fallback with the same token", () => {
    expect(out).toMatch(
      /helper = !f\(\) \{ echo username=x-access-token; echo "password=ghs_token123"; \}; f/,
    );
  });

  it("documents that it's regenerated (not a user-owned file)", () => {
    expect(out).toMatch(/Generated by agenthub-agent/);
    expect(out).toMatch(/Regenerated on every token refresh/);
  });
});
