#!/usr/bin/env bash
#
# AgentHub v2 install script.
#
# Wraps three steps behind one command so the README can say "clone + run":
#   1. pnpm install the installer package
#   2. docker build both images locally (server + workspace) unless the caller
#      pins prebuilt tags via AGENTHUB_SERVER_IMAGE and AGENTHUB_WORKSPACE_IMAGE
#   3. Runs the installer — TUI by default, `--non-interactive` passes through
#      to the Node process and consumes env vars instead.
#
# Exit codes: same as the installer (0=ok, 2=missing required env var,
# 3=install failure). Prereq failures surface as 1.

set -euo pipefail

# Surface ANY premature exit with a line number — historically this
# script's prereq checks could exit silently when stderr got eaten by a
# pty race in the curl|bash|exec chain, producing a "just stops at
# launching installer" bug. Trap fires on any error via set -e OR any
# explicit non-zero exit, and writes to both stdout and stderr so we
# still see something even if one fd is misbehaving.
trap '_rc=$?; if [[ $_rc -ne 0 ]]; then
  printf "\n[install.sh] aborted (exit %d) at line %d: %s\n" "$_rc" "$LINENO" "${BASH_COMMAND:-unknown}"
  printf "[install.sh] aborted (exit %d) at line %d: %s\n" "$_rc" "$LINENO" "${BASH_COMMAND:-unknown}" >&2
fi' EXIT

cd "$(dirname "$0")/.."

# Print each prereq check to stdout BEFORE the check runs. If anything
# exits unexpectedly, the last "checking X" line tells us where it died
# even if the conditional's error message never makes it to the log.
echo "[install.sh] checking pnpm..."
if ! command -v pnpm >/dev/null 2>&1; then
  echo "pnpm not found. Install it:" >&2
  echo "  sudo corepack enable && corepack prepare pnpm@10.12.1 --activate" >&2
  exit 1
fi

echo "[install.sh] checking docker binary..."
if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found. See docs/install/humans.md for prereqs." >&2
  exit 1
fi

echo "[install.sh] checking docker daemon reachable..."
if ! docker info >/dev/null 2>&1; then
  echo "docker daemon unreachable. Is the service running? Are you in the 'docker' group for THIS shell? (usermod -aG docker requires re-login or 'sg docker -c ...' to take effect)" >&2
  exit 1
fi

echo "=== pnpm install ==="
pnpm install --filter '@agenthub/installer...' --prefer-offline 2>&1 | tail -5

echo "=== building installer ==="
pnpm --filter @agenthub/installer build 2>&1 | tail -3

# Build images unless the caller pinned published tags.
SERVER_IMAGE="${AGENTHUB_SERVER_IMAGE:-agenthubv2-server:local}"
WORKSPACE_IMAGE="${AGENTHUB_WORKSPACE_IMAGE:-agenthubv2-workspace:local}"
export AGENTHUB_SERVER_IMAGE="$SERVER_IMAGE"
export AGENTHUB_WORKSPACE_IMAGE="$WORKSPACE_IMAGE"

if [[ "$SERVER_IMAGE" == "agenthubv2-server:local" ]]; then
  echo "=== docker build server (agenthubv2-server:local) ==="
  docker build -f docker/Dockerfile.server -t "$SERVER_IMAGE" . | tail -3
fi

if [[ "$WORKSPACE_IMAGE" == "agenthubv2-workspace:local" ]]; then
  echo "=== docker build workspace (agenthubv2-workspace:local) ==="
  docker build -f docker/Dockerfile.agent-workspace -t "$WORKSPACE_IMAGE" . | tail -3
fi

# Updater image is tiny (alpine + git + docker-cli) — always build locally,
# no registry push. The web-UI "Update" button runs this image as a one-shot
# to invoke the same agenthub CLI the operator uses from the host.
echo "=== docker build updater (agenthubv2-updater:local) ==="
docker build -q -f docker/Dockerfile.updater -t agenthubv2-updater:local . | tail -3

# --- Install the `agenthub` CLI onto PATH + state file ---------------------
# Gives the operator a single command for update/status/logs/restart after
# the install is done. Idempotent: safe to re-run across upgrades.
SUDO=""
[[ "$(id -u)" -ne 0 ]] && SUDO="sudo"
AGENTHUB_INSTALL_DIR="$(pwd)"

# Resolve the "install owner" — the uid:gid that owns the checkout and that
# post-update chown should restore. Priority:
#   1. SUDO_{UID,GID} — set by sudo when the operator did `sudo ./install.sh`
#   2. current user — non-sudo invocations run as the operator directly
#   3. stat scripts/install.sh — fallback when running as root without sudo
#      context (e.g. `sudo -i` then plain invocation); captures whichever
#      user `git clone`'d the repo.
# Used by scripts/agenthub's EXIT trap to chown repo files back after any
# root-side git/docker write, including inside the updater container where
# there is no SUDO_UID or live user to infer.
if [[ -n "${SUDO_UID:-}" ]]; then
  AGENTHUB_OWNER="${SUDO_UID}:${SUDO_GID:-$SUDO_UID}"
elif [[ "$(id -u)" -ne 0 ]]; then
  AGENTHUB_OWNER="$(id -u):$(id -g)"
else
  AGENTHUB_OWNER="$(stat -c '%u:%g' scripts/install.sh)"
fi
export AGENTHUB_OWNER

echo "=== installing agenthub CLI → /usr/local/bin/agenthub ==="
$SUDO install -m 0755 scripts/agenthub /usr/local/bin/agenthub
$SUDO mkdir -p /etc/agenthub
$SUDO tee /etc/agenthub/config >/dev/null <<EOF
# Generated by agenthub-install — used by /usr/local/bin/agenthub.
AGENTHUB_DIR=$AGENTHUB_INSTALL_DIR
AGENTHUB_OWNER=$AGENTHUB_OWNER
EOF
$SUDO chmod 0644 /etc/agenthub/config

echo "=== running installer ==="
exec node packages/installer/dist/index.js "$@"
